### PR TITLE
Task to update RHEL after all roles finish running

### PR DESCRIPTION
**Pull request by sgurnick**
Including a final step in the rhel vmware provisioning process to update the operating system.

### CODE REVIEW

**Comment by jhriv** [comment]
There should not be anything in the default template that is excluded

**Comment by cachemeoutside** [comment]
Might want to confirm that, I think the template is prepopulated with an exclude list.

**Comment by sgurnick** [comment]
It does have an exclude list configured.

**Comment by sgurnick** [comment]
@jhriv @cachemeoutside - adjustments made - please take another looks.

**Comment by cachemeoutside** [comment]
:+1: looks good to me. forgot the `needs-restarting` utility existed.

**Pull request merged**
